### ISSUE TITLE
What does stat_type do?

### ISSUE THREAD

**Issue by treeform** [david-a-wheeler/mmverify.py#1]
I am not sure what stat_type does, it only appears to be set but never read?

https://github.com/david-a-wheeler/mmverify.py/blob/master/mmverify.py#L309

**Comment by david-a-wheeler** [comment]
Whups, that's a vestigial line. It obviously won't *hurt* anything significant, but it's useless. Maybe we should comment it out, since it hints what the 0th element is.

**Comment by benjub** [comment]
Thanks. This was recalled in #4 and fixed in #7.
