### ISSUE TITLE
This software no longer works with Python 3.x

### ISSUE THREAD

**Issue by enjoysmath** [david-a-wheeler/mmverify.py#17]
Hi,

I converted all list[Type] to List[Type] where List is imported from typing, etc.  But I'm getting the following error with Python 3.x:

```
￼ File "C:\Users\fruit\OneDrive\Desktop\mmverify.py\mmverify.py", line 683, in <module>
  mm.read(Toks(db_file))
￼ File "C:\Users\fruit\OneDrive\Desktop\mmverify.py\mmverify.py", line 96, in __init__
  self.imported_files = set({pathlib.Path(str(file.name)).resolve()})
File "C:\Python38\Lib\pathlib.py", line 1159, in resolve
  s = self._flavour.resolve(self, strict=strict)
File "C:\Python38\Lib\pathlib.py", line 202, in resolve
  s = self._ext_to_normal(_getfinalpathname(s))

builtins.OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<stdin>'
```

![image](https://user-images.githubusercontent.com/1606391/177420148-d3409919-f70c-450d-98f2-4ffe55fb7895.png)

Please help me get this to run using Python 3.x.    I just want to run the verifier as a prototype for a version in the language D.

I can probably understand most of the code without the working prototype though.

**Comment by david-a-wheeler** [comment]
Can you create a pull request with the work so far?

**Comment by enjoysmath** [comment]
@david-a-wheeler I decided to instead use the mmverify.py linked to on metamath's homepage.  That one works with Python3 and is also less lines :)  I really just need a prototype to look at.  Python is not ideal proof search, mass verification, etc.  So I was going to write this in D and use pegged to specify the EBNF of Metamath.
