### ISSUE TITLE
Issues about $d variables

### ISSUE THREAD

**Issue by XiaoHLim** [david-a-wheeler/mmverify.py#26]
Hi, David. I am developing an automated theorem prover on Metamath and this repo helps me a lot. However, I feel confused on the ``$d variables``. Specifically, some theorems would not record its ``$d variables`` in ``MM.labels``. The first theorem in ``set.mm`` that doesn't record the ``$d variables `` is ``exgen``, whose assertion is:

```python
(set(), [('wff', 'ph'), ('setvar', 'x')], [['|-', 'ph']], ['|-', 'E.', 'x', 'ph'])
```

and it's statement in ``set.mm`` is as below:

```metamath
  ${
    $d x y $.
    exgen.1 $e |- ph $.
    $( Rule of existential generalization, ... $)
    exgen $p |- E. x ph $=
      ( vy weq idd speiv ) AABDBDEAFCG $.

    ...

  $}
```

The assertion is returned by ``make_assertion()`` in L264. This function only checks the variables in ``e_hyps`` and ``stmt`` and constructs ``$d``, so it's an expected behavior to not have ``(x, y)`` as a ``$d`` pair (since ``y`` does not appear in either ``e_hyps`` or ``stmt``). However, when I try to convert FullStmt to a theorem in set.mm and call the ``MM.read()`` method to verify, I pass in a string like this (all the necessary ``$c, $v``s have been defined):

```metamath
  ${
    $( No explicit declare: $d x y $. $) 
    exgen.1 $e |- ph $.
    exgen $p |- E. x ph $=
      ( vy weq idd speiv ) AABDBDEAFCG $.
  $}
```

and it raise a ``MMError: Disjoint variable violation: x , y``.

I don't know how other languages' implementations of the metamath verifiers handle the above case, but I think the above theorem should pass the verification. 

Here are my questions:

- For a theorem whose ``$d`` involves at least one variable that does not appear in its statement (``e_hyps`` and ``stmt``), does removing this ``$d`` restriction not change the semantics? (Personally, I think this is correct.)

- If the first thing is correct, should we introduce the concept of ``free $d`` and modify ``MM.verify()`` method? For theorems whose ``$d`` involves at least one variable that does not appear in its statement, even if the ``$d`` is not declared, the modified verifier would automatically derive and verify this restriction when proving the theorem. (I am honored to implement this feature and contribute to this repo!)

**Comment by tirix** [comment]
Hi Lin Xiaohan,

This is a valid question which has been raised in the past.
[This discussion](https://groups.google.com/g/metamath/c/M2dUfFATxD8?pli=1) is probably relevant: 
> _the Metamath spec requires that any disjoint variable conditions between dummies are required to be mentioned in the .mm file, although they are elided in the HTML proof display and they do not transfer to users of a theorem._

**Comment by XiaoHLim** [comment]
I see. Thank you for your timely reply!
